spring.application.name=support bot data ingestion


spring.ai.vertex.ai.gemini.project-id=${google_cloud_project_id}
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.transport=REST

spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash-lite

spring.ai.vertex.ai.embedding.project-id=${google_cloud_project_id}
spring.ai.vertex.ai.embedding.location=us-central1
spring.ai.vertex.ai.embedding.text.options.model=gemini-embedding-001

spring.datasource.url=${postgresql_db_url}
spring.datasource.username=postgres
spring.datasource.password=${postgresql_db_password}

management.endpoints.web.exposure.include=*
